# Generated by Django 5.2.1 on 2026-10-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_protocol_manufacture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolmeasurement',
            name='pneumatic_suspension_present',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
